// Writes the starter spots as a SQL migration, so the shared database begins with the same
// places the app used to keep in each visitor's browser.
//   pnpm --filter @workspace/scripts run export-seed-sql
import { writeFileSync } from "node:fs";
import path from "node:path";
import { SEED_DATA } from "../../artifacts/atlas/src/lib/seed-data";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const j = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

const rows = SEED_DATA.map((s) =>
  `  (${q(s.id)}, ${q(s.name)}, ${q(s.category)}, ${q(s.city)}, ${q(s.address)}, ${s.lat}, ${s.lng}, ${j(s.scores)}, array[${s.tags.map(q).join(", ")}]::text[], ${q(s.description)}, ${s.aiSummary ? q(s.aiSummary) : "null"}, ${s.operatingHours ? j(s.operatingHours) : "null"}, ${q(s.submittedAt)})`,
);

const sql = `-- Starter spots, generated by scripts/src/export-seed-sql.ts from the app's original seed data.
insert into public.spots (id, name, category, city, address, lat, lng, scores, tags, description, ai_summary, operating_hours, created_at)
values
${rows.join(",\n")}
on conflict (id) do nothing;
`;

const out = path.resolve(import.meta.dirname, "../../supabase/migrations/20260927000100_seed_spots.sql");
writeFileSync(out, sql);
console.log(`Wrote ${SEED_DATA.length} spots to ${path.relative(process.cwd(), out)}`);
